version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: server
    mod_timestamp: "{{ .CommitTimestamp }}"
    dir: ./cmd/server
    binary: server
    flags:
      - -trimpath
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  name_template: "v{{ .Version }}"

dockers_v2:
  - id: server
    sbom: false
    platforms:
      - linux/amd64
    ids:
      - server
    dockerfile: misc/release/Dockerfile
    images:
      - "ghcr.io/{{ tolower ( .Env.REPO_OWNER ) }}/gowebdav-server"
    tags:
      - "{{ .Version }}"
      - latest
    extra_files:
      - misc/release/config.json
